START TRANSACTION;

ALTER TABLE `Log` DROP FOREIGN KEY `FK_Log_LogType_LogTypeId`;

ALTER TABLE `Log` DROP INDEX `IX_Log_LogTypeId`;

ALTER TABLE `LogType` RENAME COLUMN `LogTypeId` TO `Id`;

ALTER TABLE `Log` RENAME COLUMN `LogId` TO `Id`;

ALTER TABLE `Log` ADD CONSTRAINT `FK_Log_LogType_Id` FOREIGN KEY (`Id`) REFERENCES `LogType` (`Id`) ON DELETE CASCADE;

INSERT INTO `__EFMigrationsHistory` (`MigrationId`, `ProductVersion`)
VALUES ('20240303224043_BaseChange', '8.0.2');

COMMIT;

